# Generated by Django 3.2.7 on 2021-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocate', '0002_alter_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
