# Generated by Django 3.2.7 on 2021-09-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocate', '0003_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=None, max_length=1),
        ),
    ]
