# Generated by Django 3.2.7 on 2021-09-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocate', '0004_auto_20210908_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
