# Generated by Django 3.2.7 on 2021-09-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relocate', '0005_auto_20210908_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='relocate.location'),
        ),
    ]
