# Generated by Django 3.2.7 on 2021-09-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocate', '0006_alter_comment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.TextField(default='', max_length=800),
        ),
    ]
